//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Babe.Lua.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Babe.Lua.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Can not create tool window. 的本地化字符串。
        /// </summary>
        internal static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} will be delete. Please confirm. 的本地化字符串。
        /// </summary>
        internal static string DeleteFileConfirm {
            get {
                return ResourceManager.GetString("DeleteFileConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure Delete？ 的本地化字符串。
        /// </summary>
        internal static string DeleteSetConfirm {
            get {
                return ResourceManager.GetString("DeleteSetConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder Explorer 的本地化字符串。
        /// </summary>
        internal static string FolderWindowTitle {
            get {
                return ResourceManager.GetString("FolderWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have to set lua executable path first. 的本地化字符串。
        /// </summary>
        internal static string GuideLuaExecutablePath {
            get {
                return ResourceManager.GetString("GuideLuaExecutablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find lua executable in target path. 的本地化字符串。
        /// </summary>
        internal static string InvalidLuaExecutablePath {
            get {
                return ResourceManager.GetString("InvalidLuaExecutablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid lua folder. 的本地化字符串。
        /// </summary>
        internal static string InvalidLuaPath {
            get {
                return ResourceManager.GetString("InvalidLuaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Input Lua Folder 的本地化字符串。
        /// </summary>
        internal static string LoseLuaPath {
            get {
                return ResourceManager.GetString("LoseLuaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Input Name 的本地化字符串。
        /// </summary>
        internal static string LoseSetName {
            get {
                return ResourceManager.GetString("LoseSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run Failed. Result is：{0} 的本地化字符串。
        /// </summary>
        internal static string LuaExecutableError {
            get {
                return ResourceManager.GetString("LuaExecutableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outline Explorer 的本地化字符串。
        /// </summary>
        internal static string OutlineWindowTitle {
            get {
                return ResourceManager.GetString("OutlineWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A Setting with this name already exists 的本地化字符串。
        /// </summary>
        internal static string RepeatSetName {
            get {
                return ResourceManager.GetString("RepeatSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Result 1 的本地化字符串。
        /// </summary>
        internal static string SearchlWindowTitle1 {
            get {
                return ResourceManager.GetString("SearchlWindowTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Result 2 的本地化字符串。
        /// </summary>
        internal static string SearchlWindowTitle2 {
            get {
                return ResourceManager.GetString("SearchlWindowTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!--You should never modify this file by yourself--&gt;
        ///&lt;Settings&gt;
        ///	&lt;LuaSettings&gt;
        ///		&lt;CurrentSet&gt;&lt;/CurrentSet&gt;
        ///	&lt;/LuaSettings&gt;
        ///	&lt;SearchFilters&gt;
        ///		&lt;local /&gt;
        ///		&lt;do /&gt;
        ///		&lt;while /&gt;
        ///		&lt;for /&gt;
        ///		&lt;end /&gt;
        ///		&lt;function /&gt;
        ///		&lt;if /&gt;
        ///		&lt;then /&gt;
        ///		&lt;elseif /&gt;
        ///		&lt;and /&gt;
        ///		&lt;or /&gt;
        ///		&lt;not /&gt;
        ///		&lt;true /&gt;
        ///		&lt;false /&gt;
        ///		&lt;nil /&gt;
        ///		&lt;return /&gt;
        ///		&lt;repeat /&gt;
        ///		&lt;until /&gt;
        ///		&lt;in /&gt;
        ///		&lt;break /&gt;
        ///	&lt;/SearchFilters&gt;
        ///	&lt;UISettings&gt;
        ///		&lt;HideUselessView&gt;0&lt;/HideUselessView&gt;
        ///	&lt;/UISetti [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string SettingWindotTitle {
            get {
                return ResourceManager.GetString("SettingWindotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--You must restart visual studio for the changes to take effect--&gt;
        ///&lt;Keywords&gt;
        ///	&lt;!--support at most 15 groups--&gt;
        ///	&lt;User r=&quot;0&quot; g=&quot;0&quot; b=&quot;255&quot;&gt;
        ///		&lt;word&gt;add_your_keyword_like_this&lt;/word&gt;
        ///	&lt;/User&gt;
        ///	&lt;User r=&quot;255&quot; g=&quot;0&quot; b=&quot;0&quot;&gt;
        ///		&lt;word&gt;add_your_keyword_like_this&lt;/word&gt;
        ///	&lt;/User&gt;
        ///&lt;/Keywords&gt; 的本地化字符串。
        /// </summary>
        internal static string UserKeyWords {
            get {
                return ResourceManager.GetString("UserKeyWords", resourceCulture);
            }
        }
    }
}
